// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package twoonone

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	twoononeFieldNames          = builder.RawFieldNames(&Twoonone{})
	twoononeRows                = strings.Join(twoononeFieldNames, ",")
	twoononeRowsExpectAutoSet   = strings.Join(stringx.Remove(twoononeFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	twoononeRowsWithPlaceHolder = strings.Join(stringx.Remove(twoononeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	twoononeModel interface {
		Insert(ctx context.Context, data *Twoonone) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Twoonone, error)
		Update(ctx context.Context, data *Twoonone) error
		Delete(ctx context.Context, id string) error
	}

	defaultTwoononeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Twoonone struct {
		Id               string  `db:"id"`
		Wincount         int64   `db:"wincount"`
		Losecount        int64   `db:"losecount"`
		LastGetdaliyTime int64   `db:"last_getdaliy_time"`
		Coin             float64 `db:"coin"`
	}
)

func newTwoononeModel(conn sqlx.SqlConn) *defaultTwoononeModel {
	return &defaultTwoononeModel{
		conn:  conn,
		table: "`twoonone`",
	}
}

func (m *defaultTwoononeModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTwoononeModel) FindOne(ctx context.Context, id string) (*Twoonone, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", twoononeRows, m.table)
	var resp Twoonone
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTwoononeModel) Insert(ctx context.Context, data *Twoonone) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, twoononeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Wincount, data.Losecount, data.LastGetdaliyTime, data.Coin)
	return ret, err
}

func (m *defaultTwoononeModel) Update(ctx context.Context, data *Twoonone) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, twoononeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Wincount, data.Losecount, data.LastGetdaliyTime, data.Coin, data.Id)
	return err
}

func (m *defaultTwoononeModel) tableName() string {
	return m.table
}
