// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: handler/LLOneBot/protos/handler/response/response.proto

package response

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResponseHandler_BotResponseUnmarshal_FullMethodName = "/ResponseHandler/BotResponseUnmarshal"
)

// ResponseHandlerClient is the client API for ResponseHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResponseHandlerClient interface {
	BotResponseUnmarshal(ctx context.Context, in *BotResponseUnmarshalRequest, opts ...grpc.CallOption) (*BotResponseUnmarshalResponse, error)
}

type responseHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewResponseHandlerClient(cc grpc.ClientConnInterface) ResponseHandlerClient {
	return &responseHandlerClient{cc}
}

func (c *responseHandlerClient) BotResponseUnmarshal(ctx context.Context, in *BotResponseUnmarshalRequest, opts ...grpc.CallOption) (*BotResponseUnmarshalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotResponseUnmarshalResponse)
	err := c.cc.Invoke(ctx, ResponseHandler_BotResponseUnmarshal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResponseHandlerServer is the server API for ResponseHandler service.
// All implementations must embed UnimplementedResponseHandlerServer
// for forward compatibility.
type ResponseHandlerServer interface {
	BotResponseUnmarshal(context.Context, *BotResponseUnmarshalRequest) (*BotResponseUnmarshalResponse, error)
	mustEmbedUnimplementedResponseHandlerServer()
}

// UnimplementedResponseHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResponseHandlerServer struct{}

func (UnimplementedResponseHandlerServer) BotResponseUnmarshal(context.Context, *BotResponseUnmarshalRequest) (*BotResponseUnmarshalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BotResponseUnmarshal not implemented")
}
func (UnimplementedResponseHandlerServer) mustEmbedUnimplementedResponseHandlerServer() {}
func (UnimplementedResponseHandlerServer) testEmbeddedByValue()                         {}

// UnsafeResponseHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResponseHandlerServer will
// result in compilation errors.
type UnsafeResponseHandlerServer interface {
	mustEmbedUnimplementedResponseHandlerServer()
}

func RegisterResponseHandlerServer(s grpc.ServiceRegistrar, srv ResponseHandlerServer) {
	// If the following call pancis, it indicates UnimplementedResponseHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResponseHandler_ServiceDesc, srv)
}

func _ResponseHandler_BotResponseUnmarshal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotResponseUnmarshalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResponseHandlerServer).BotResponseUnmarshal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResponseHandler_BotResponseUnmarshal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResponseHandlerServer).BotResponseUnmarshal(ctx, req.(*BotResponseUnmarshalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResponseHandler_ServiceDesc is the grpc.ServiceDesc for ResponseHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResponseHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ResponseHandler",
	HandlerType: (*ResponseHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BotResponseUnmarshal",
			Handler:    _ResponseHandler_BotResponseUnmarshal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "handler/LLOneBot/protos/handler/response/response.proto",
}
