// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: randomfortune.proto

package server

import (
	"context"

	"github.com/nanachi-sh/susubot-code/plugin/randomfortune/pkg/protos/randomfortune"
	"github.com/nanachi-sh/susubot-code/plugin/randomfortune/service/internal/logic"
	"github.com/nanachi-sh/susubot-code/plugin/randomfortune/service/internal/svc"
)

type RandomFortuneServer struct {
	svcCtx *svc.ServiceContext
	randomfortune.UnimplementedRandomFortuneServer
}

func NewRandomFortuneServer(svcCtx *svc.ServiceContext) *RandomFortuneServer {
	return &RandomFortuneServer{
		svcCtx: svcCtx,
	}
}

func (s *RandomFortuneServer) GetFortune(ctx context.Context, in *randomfortune.BasicRequest) (*randomfortune.BasicResponse, error) {
	l := logic.NewGetFortuneLogic(ctx, s.svcCtx)
	return l.GetFortune(in)
}
