// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: plugin/randomAnimal/LLOneBot/protos/randomAnimal/randomanimal.proto

package randomAnimal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_Image Type = 0
	Type_Video Type = 1
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "Image",
		1: "Video",
	}
	Type_value = map[string]int32{
		"Image": 0,
		"Video": 1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_rawDescGZIP(), []int{0}
}

type BasicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Type   `protobuf:"varint,1,opt,name=Type,proto3,enum=Type" json:"Type,omitempty"`
	Buf  []byte `protobuf:"bytes,2,opt,name=Buf,proto3" json:"Buf,omitempty"`
}

func (x *BasicResponse) Reset() {
	*x = BasicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicResponse) ProtoMessage() {}

func (x *BasicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicResponse.ProtoReflect.Descriptor instead.
func (*BasicResponse) Descriptor() ([]byte, []int) {
	return file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_rawDescGZIP(), []int{1}
}

func (x *BasicResponse) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_Image
}

func (x *BasicResponse) GetBuf() []byte {
	if x != nil {
		return x.Buf
	}
	return nil
}

var File_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto protoreflect.FileDescriptor

var file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_rawDesc = []byte{
	0x0a, 0x43, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x41,
	0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x2f, 0x4c, 0x4c, 0x4f, 0x6e, 0x65, 0x42, 0x6f, 0x74, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x41, 0x6e, 0x69, 0x6d,
	0x61, 0x6c, 0x2f, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x3c,
	0x0a, 0x0d, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x19, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x05, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x42, 0x75,
	0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x42, 0x75, 0x66, 0x2a, 0x1c, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x10, 0x01, 0x32, 0xc0, 0x01, 0x0a, 0x0c, 0x72,
	0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x06, 0x47,
	0x65, 0x74, 0x44, 0x6f, 0x67, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0e, 0x2e,
	0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x78, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x0e, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x21, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x44, 0x75, 0x63, 0x6b, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x0e, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x20, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x12, 0x06, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0e, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x68, 0x69, 0x6b, 0x65,
	0x6e, 0x5f, 0x43, 0x58, 0x4b, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0e, 0x2e,
	0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x55, 0x5a,
	0x53, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x6e, 0x61,
	0x63, 0x68, 0x69, 0x2d, 0x73, 0x68, 0x2f, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2d, 0x63,
	0x6f, 0x64, 0x65, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x72, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x2f, 0x4c, 0x4c, 0x4f, 0x6e, 0x65, 0x42, 0x6f, 0x74,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x41, 0x6e,
	0x69, 0x6d, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_rawDescOnce sync.Once
	file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_rawDescData = file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_rawDesc
)

func file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_rawDescGZIP() []byte {
	file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_rawDescOnce.Do(func() {
		file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_rawDescData = protoimpl.X.CompressGZIP(file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_rawDescData)
	})
	return file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_rawDescData
}

var file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_goTypes = []any{
	(Type)(0),             // 0: Type
	(*Empty)(nil),         // 1: Empty
	(*BasicResponse)(nil), // 2: BasicResponse
}
var file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_depIdxs = []int32{
	0, // 0: BasicResponse.Type:type_name -> Type
	1, // 1: randomAnimal.GetDog:input_type -> Empty
	1, // 2: randomAnimal.GetFox:input_type -> Empty
	1, // 3: randomAnimal.GetDuck:input_type -> Empty
	1, // 4: randomAnimal.GetCat:input_type -> Empty
	1, // 5: randomAnimal.GetChiken_CXK:input_type -> Empty
	2, // 6: randomAnimal.GetDog:output_type -> BasicResponse
	2, // 7: randomAnimal.GetFox:output_type -> BasicResponse
	2, // 8: randomAnimal.GetDuck:output_type -> BasicResponse
	2, // 9: randomAnimal.GetCat:output_type -> BasicResponse
	2, // 10: randomAnimal.GetChiken_CXK:output_type -> BasicResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_init() }
func file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_init() {
	if File_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BasicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_goTypes,
		DependencyIndexes: file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_depIdxs,
		EnumInfos:         file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_enumTypes,
		MessageInfos:      file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_msgTypes,
	}.Build()
	File_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto = out.File
	file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_rawDesc = nil
	file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_goTypes = nil
	file_plugin_randomAnimal_LLOneBot_protos_randomAnimal_randomanimal_proto_depIdxs = nil
}
