// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type UserRegisterRequest struct {
	VerifyCode string `form:"verify_code"`
	Email      string `form:"email"`
	Password   string `form:"password"`
}

type UserVerifyCodeEmailRequest struct {
	Email string `form:"email"`
}

type VerifyCodeAuthMiddlewareRequest struct {
	VerifyId string `form:"verify_id"`
	Answer   string `form:"answer"`
}

type VerifyCodeResponse struct {
	B64      string
	VerifyId string
}
