// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: handler/LLOneBot/protos/handler/define.proto

package handler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseType int32

const (
	ResponseType_ResponseType_Message  ResponseType = 0 //消息事件
	ResponseType_ResponseType_QQEvent  ResponseType = 1 //QQ事件
	ResponseType_ResponseType_CmdEvent ResponseType = 2 //命令响应
	ResponseType_ResponseType_BotEvent ResponseType = 3 //机器人事件
)

// Enum value maps for ResponseType.
var (
	ResponseType_name = map[int32]string{
		0: "ResponseType_Message",
		1: "ResponseType_QQEvent",
		2: "ResponseType_CmdEvent",
		3: "ResponseType_BotEvent",
	}
	ResponseType_value = map[string]int32{
		"ResponseType_Message":  0,
		"ResponseType_QQEvent":  1,
		"ResponseType_CmdEvent": 2,
		"ResponseType_BotEvent": 3,
	}
)

func (x ResponseType) Enum() *ResponseType {
	p := new(ResponseType)
	*p = x
	return p
}

func (x ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_handler_LLOneBot_protos_handler_define_proto_enumTypes[0].Descriptor()
}

func (ResponseType) Type() protoreflect.EnumType {
	return &file_handler_LLOneBot_protos_handler_define_proto_enumTypes[0]
}

func (x ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseType.Descriptor instead.
func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_MessageType_Private MessageType = 0 //私聊消息
	MessageType_MessageType_Group   MessageType = 1 //群组消息
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MessageType_Private",
		1: "MessageType_Group",
	}
	MessageType_value = map[string]int32{
		"MessageType_Private": 0,
		"MessageType_Group":   1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_handler_LLOneBot_protos_handler_define_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_handler_LLOneBot_protos_handler_define_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP(), []int{1}
}

type MessageChainType int32

const (
	MessageChainType_MessageChainType_Text  MessageChainType = 0 //纯文本
	MessageChainType_MessageChainType_Image MessageChainType = 1 //图片 or 动图
	MessageChainType_MessageChainType_Voice MessageChainType = 2 //语音
	MessageChainType_MessageChainType_Video MessageChainType = 3 //视频
	MessageChainType_MessageChainType_At    MessageChainType = 4 //At
	MessageChainType_MessageChainType_Reply MessageChainType = 5 //回复
)

// Enum value maps for MessageChainType.
var (
	MessageChainType_name = map[int32]string{
		0: "MessageChainType_Text",
		1: "MessageChainType_Image",
		2: "MessageChainType_Voice",
		3: "MessageChainType_Video",
		4: "MessageChainType_At",
		5: "MessageChainType_Reply",
	}
	MessageChainType_value = map[string]int32{
		"MessageChainType_Text":  0,
		"MessageChainType_Image": 1,
		"MessageChainType_Voice": 2,
		"MessageChainType_Video": 3,
		"MessageChainType_At":    4,
		"MessageChainType_Reply": 5,
	}
)

func (x MessageChainType) Enum() *MessageChainType {
	p := new(MessageChainType)
	*p = x
	return p
}

func (x MessageChainType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageChainType) Descriptor() protoreflect.EnumDescriptor {
	return file_handler_LLOneBot_protos_handler_define_proto_enumTypes[2].Descriptor()
}

func (MessageChainType) Type() protoreflect.EnumType {
	return &file_handler_LLOneBot_protos_handler_define_proto_enumTypes[2]
}

func (x MessageChainType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageChainType.Descriptor instead.
func (MessageChainType) EnumDescriptor() ([]byte, []int) {
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP(), []int{2}
}

type QQEventType int32

const (
	QQEventType_QQEventType_GroupAdd      QQEventType = 0 //群聊成员增加
	QQEventType_QQEventType_GroupRemove   QQEventType = 1 //群聊成员减少
	QQEventType_QQEventType_GroupMute     QQEventType = 2 //群聊成员被禁言
	QQEventType_QQEventType_GroupUnmute   QQEventType = 3 //群聊成员被解除禁言
	QQEventType_QQEventType_MessageRecall QQEventType = 4 //消息撤回
)

// Enum value maps for QQEventType.
var (
	QQEventType_name = map[int32]string{
		0: "QQEventType_GroupAdd",
		1: "QQEventType_GroupRemove",
		2: "QQEventType_GroupMute",
		3: "QQEventType_GroupUnmute",
		4: "QQEventType_MessageRecall",
	}
	QQEventType_value = map[string]int32{
		"QQEventType_GroupAdd":      0,
		"QQEventType_GroupRemove":   1,
		"QQEventType_GroupMute":     2,
		"QQEventType_GroupUnmute":   3,
		"QQEventType_MessageRecall": 4,
	}
)

func (x QQEventType) Enum() *QQEventType {
	p := new(QQEventType)
	*p = x
	return p
}

func (x QQEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QQEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_handler_LLOneBot_protos_handler_define_proto_enumTypes[3].Descriptor()
}

func (QQEventType) Type() protoreflect.EnumType {
	return &file_handler_LLOneBot_protos_handler_define_proto_enumTypes[3]
}

func (x QQEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QQEventType.Descriptor instead.
func (QQEventType) EnumDescriptor() ([]byte, []int) {
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP(), []int{3}
}

type QQEventType_GroupAddType int32

const (
	QQEventType_GroupAddType_QQEventType_GroupAddType_Direct QQEventType_GroupAddType = 0 //直接加入群聊
	QQEventType_GroupAddType_QQEventType_GroupAddType_Invite QQEventType_GroupAddType = 1 //群聊成员邀请加入
)

// Enum value maps for QQEventType_GroupAddType.
var (
	QQEventType_GroupAddType_name = map[int32]string{
		0: "QQEventType_GroupAddType_Direct",
		1: "QQEventType_GroupAddType_Invite",
	}
	QQEventType_GroupAddType_value = map[string]int32{
		"QQEventType_GroupAddType_Direct": 0,
		"QQEventType_GroupAddType_Invite": 1,
	}
)

func (x QQEventType_GroupAddType) Enum() *QQEventType_GroupAddType {
	p := new(QQEventType_GroupAddType)
	*p = x
	return p
}

func (x QQEventType_GroupAddType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QQEventType_GroupAddType) Descriptor() protoreflect.EnumDescriptor {
	return file_handler_LLOneBot_protos_handler_define_proto_enumTypes[4].Descriptor()
}

func (QQEventType_GroupAddType) Type() protoreflect.EnumType {
	return &file_handler_LLOneBot_protos_handler_define_proto_enumTypes[4]
}

func (x QQEventType_GroupAddType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QQEventType_GroupAddType.Descriptor instead.
func (QQEventType_GroupAddType) EnumDescriptor() ([]byte, []int) {
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP(), []int{4}
}

type QQEventType_GroupRemoveType int32

const (
	QQEventType_GroupRemoveType_QQEventType_GroupRemoveType_Manual QQEventType_GroupRemoveType = 0 //主动退出群聊
	QQEventType_GroupRemoveType_QQEventType_GroupRemoveType_Kick   QQEventType_GroupRemoveType = 1 //被踢出群聊
)

// Enum value maps for QQEventType_GroupRemoveType.
var (
	QQEventType_GroupRemoveType_name = map[int32]string{
		0: "QQEventType_GroupRemoveType_Manual",
		1: "QQEventType_GroupRemoveType_Kick",
	}
	QQEventType_GroupRemoveType_value = map[string]int32{
		"QQEventType_GroupRemoveType_Manual": 0,
		"QQEventType_GroupRemoveType_Kick":   1,
	}
)

func (x QQEventType_GroupRemoveType) Enum() *QQEventType_GroupRemoveType {
	p := new(QQEventType_GroupRemoveType)
	*p = x
	return p
}

func (x QQEventType_GroupRemoveType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QQEventType_GroupRemoveType) Descriptor() protoreflect.EnumDescriptor {
	return file_handler_LLOneBot_protos_handler_define_proto_enumTypes[5].Descriptor()
}

func (QQEventType_GroupRemoveType) Type() protoreflect.EnumType {
	return &file_handler_LLOneBot_protos_handler_define_proto_enumTypes[5]
}

func (x QQEventType_GroupRemoveType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QQEventType_GroupRemoveType.Descriptor instead.
func (QQEventType_GroupRemoveType) EnumDescriptor() ([]byte, []int) {
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP(), []int{5}
}

type QQEventType_MessageRecallType int32

const (
	QQEventType_MessageRecallType_QQEventType_MessageRecallType_Group   QQEventType_MessageRecallType = 0 //群聊消息撤回
	QQEventType_MessageRecallType_QQEventType_MessageRecallType_Private QQEventType_MessageRecallType = 1 //私聊消息撤回
)

// Enum value maps for QQEventType_MessageRecallType.
var (
	QQEventType_MessageRecallType_name = map[int32]string{
		0: "QQEventType_MessageRecallType_Group",
		1: "QQEventType_MessageRecallType_Private",
	}
	QQEventType_MessageRecallType_value = map[string]int32{
		"QQEventType_MessageRecallType_Group":   0,
		"QQEventType_MessageRecallType_Private": 1,
	}
)

func (x QQEventType_MessageRecallType) Enum() *QQEventType_MessageRecallType {
	p := new(QQEventType_MessageRecallType)
	*p = x
	return p
}

func (x QQEventType_MessageRecallType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QQEventType_MessageRecallType) Descriptor() protoreflect.EnumDescriptor {
	return file_handler_LLOneBot_protos_handler_define_proto_enumTypes[6].Descriptor()
}

func (QQEventType_MessageRecallType) Type() protoreflect.EnumType {
	return &file_handler_LLOneBot_protos_handler_define_proto_enumTypes[6]
}

func (x QQEventType_MessageRecallType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QQEventType_MessageRecallType.Descriptor instead.
func (QQEventType_MessageRecallType) EnumDescriptor() ([]byte, []int) {
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP(), []int{6}
}

type CmdEventType int32

const (
	CmdEventType_CmdEventType_GetGroupInfo       CmdEventType = 0 //获取指定群聊信息
	CmdEventType_CmdEventType_GetGroupMemberInfo CmdEventType = 1 //获取指定群聊指定成员信息
	CmdEventType_CmdEventType_GetMessage         CmdEventType = 2 //获取消息事件(通过MessageId)
	CmdEventType_CmdEventType_GetFriendList      CmdEventType = 3 //获取所有好友信息
	CmdEventType_CmdEventType_GetFriendInfo      CmdEventType = 4 //
)

// Enum value maps for CmdEventType.
var (
	CmdEventType_name = map[int32]string{
		0: "CmdEventType_GetGroupInfo",
		1: "CmdEventType_GetGroupMemberInfo",
		2: "CmdEventType_GetMessage",
		3: "CmdEventType_GetFriendList",
		4: "CmdEventType_GetFriendInfo",
	}
	CmdEventType_value = map[string]int32{
		"CmdEventType_GetGroupInfo":       0,
		"CmdEventType_GetGroupMemberInfo": 1,
		"CmdEventType_GetMessage":         2,
		"CmdEventType_GetFriendList":      3,
		"CmdEventType_GetFriendInfo":      4,
	}
)

func (x CmdEventType) Enum() *CmdEventType {
	p := new(CmdEventType)
	*p = x
	return p
}

func (x CmdEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_handler_LLOneBot_protos_handler_define_proto_enumTypes[7].Descriptor()
}

func (CmdEventType) Type() protoreflect.EnumType {
	return &file_handler_LLOneBot_protos_handler_define_proto_enumTypes[7]
}

func (x CmdEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdEventType.Descriptor instead.
func (CmdEventType) EnumDescriptor() ([]byte, []int) {
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP(), []int{7}
}

type BotEventType int32

const (
	BotEventType_BotEventType_HeartPacket BotEventType = 0
	BotEventType_BotEventType_Connected   BotEventType = 1
)

// Enum value maps for BotEventType.
var (
	BotEventType_name = map[int32]string{
		0: "BotEventType_HeartPacket",
		1: "BotEventType_Connected",
	}
	BotEventType_value = map[string]int32{
		"BotEventType_HeartPacket": 0,
		"BotEventType_Connected":   1,
	}
)

func (x BotEventType) Enum() *BotEventType {
	p := new(BotEventType)
	*p = x
	return p
}

func (x BotEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BotEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_handler_LLOneBot_protos_handler_define_proto_enumTypes[8].Descriptor()
}

func (BotEventType) Type() protoreflect.EnumType {
	return &file_handler_LLOneBot_protos_handler_define_proto_enumTypes[8]
}

func (x BotEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BotEventType.Descriptor instead.
func (BotEventType) EnumDescriptor() ([]byte, []int) {
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP(), []int{8}
}

type GroupRole int32

const (
	GroupRole_GroupRole_Member GroupRole = 0 //普通成员
	GroupRole_GroupRole_Admin  GroupRole = 1 //管理员
	GroupRole_GroupRole_Owner  GroupRole = 2 //群主
)

// Enum value maps for GroupRole.
var (
	GroupRole_name = map[int32]string{
		0: "GroupRole_Member",
		1: "GroupRole_Admin",
		2: "GroupRole_Owner",
	}
	GroupRole_value = map[string]int32{
		"GroupRole_Member": 0,
		"GroupRole_Admin":  1,
		"GroupRole_Owner":  2,
	}
)

func (x GroupRole) Enum() *GroupRole {
	p := new(GroupRole)
	*p = x
	return p
}

func (x GroupRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupRole) Descriptor() protoreflect.EnumDescriptor {
	return file_handler_LLOneBot_protos_handler_define_proto_enumTypes[9].Descriptor()
}

func (GroupRole) Type() protoreflect.EnumType {
	return &file_handler_LLOneBot_protos_handler_define_proto_enumTypes[9]
}

func (x GroupRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupRole.Descriptor instead.
func (GroupRole) EnumDescriptor() ([]byte, []int) {
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP(), []int{9}
}

type MessageChainObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  *MessageChainType   `protobuf:"varint,1,opt,name=Type,proto3,enum=define.MessageChainType,oneof" json:"Type,omitempty"`
	Text  *MessageChain_Text  `protobuf:"bytes,2,opt,name=Text,proto3,oneof" json:"Text,omitempty"`
	Image *MessageChain_Image `protobuf:"bytes,3,opt,name=Image,proto3,oneof" json:"Image,omitempty"`
	Voice *MessageChain_Voice `protobuf:"bytes,4,opt,name=Voice,proto3,oneof" json:"Voice,omitempty"`
	Video *MessageChain_Video `protobuf:"bytes,5,opt,name=Video,proto3,oneof" json:"Video,omitempty"`
	At    *MessageChain_At    `protobuf:"bytes,6,opt,name=At,proto3,oneof" json:"At,omitempty"`
	Reply *MessageChain_Reply `protobuf:"bytes,7,opt,name=Reply,proto3,oneof" json:"Reply,omitempty"`
}

func (x *MessageChainObject) Reset() {
	*x = MessageChainObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handler_LLOneBot_protos_handler_define_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageChainObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageChainObject) ProtoMessage() {}

func (x *MessageChainObject) ProtoReflect() protoreflect.Message {
	mi := &file_handler_LLOneBot_protos_handler_define_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageChainObject.ProtoReflect.Descriptor instead.
func (*MessageChainObject) Descriptor() ([]byte, []int) {
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP(), []int{0}
}

func (x *MessageChainObject) GetType() MessageChainType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return MessageChainType_MessageChainType_Text
}

func (x *MessageChainObject) GetText() *MessageChain_Text {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *MessageChainObject) GetImage() *MessageChain_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *MessageChainObject) GetVoice() *MessageChain_Voice {
	if x != nil {
		return x.Voice
	}
	return nil
}

func (x *MessageChainObject) GetVideo() *MessageChain_Video {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *MessageChainObject) GetAt() *MessageChain_At {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *MessageChainObject) GetReply() *MessageChain_Reply {
	if x != nil {
		return x.Reply
	}
	return nil
}

type MessageChain_Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=Text,proto3" json:"Text,omitempty"`
}

func (x *MessageChain_Text) Reset() {
	*x = MessageChain_Text{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handler_LLOneBot_protos_handler_define_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageChain_Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageChain_Text) ProtoMessage() {}

func (x *MessageChain_Text) ProtoReflect() protoreflect.Message {
	mi := &file_handler_LLOneBot_protos_handler_define_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageChain_Text.ProtoReflect.Descriptor instead.
func (*MessageChain_Text) Descriptor() ([]byte, []int) {
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP(), []int{1}
}

func (x *MessageChain_Text) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type MessageChain_Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URL string `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
}

func (x *MessageChain_Image) Reset() {
	*x = MessageChain_Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handler_LLOneBot_protos_handler_define_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageChain_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageChain_Image) ProtoMessage() {}

func (x *MessageChain_Image) ProtoReflect() protoreflect.Message {
	mi := &file_handler_LLOneBot_protos_handler_define_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageChain_Image.ProtoReflect.Descriptor instead.
func (*MessageChain_Image) Descriptor() ([]byte, []int) {
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP(), []int{2}
}

func (x *MessageChain_Image) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type MessageChain_Voice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URL string `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
}

func (x *MessageChain_Voice) Reset() {
	*x = MessageChain_Voice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handler_LLOneBot_protos_handler_define_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageChain_Voice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageChain_Voice) ProtoMessage() {}

func (x *MessageChain_Voice) ProtoReflect() protoreflect.Message {
	mi := &file_handler_LLOneBot_protos_handler_define_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageChain_Voice.ProtoReflect.Descriptor instead.
func (*MessageChain_Voice) Descriptor() ([]byte, []int) {
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP(), []int{3}
}

func (x *MessageChain_Voice) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type MessageChain_Video struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URL string `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
}

func (x *MessageChain_Video) Reset() {
	*x = MessageChain_Video{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handler_LLOneBot_protos_handler_define_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageChain_Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageChain_Video) ProtoMessage() {}

func (x *MessageChain_Video) ProtoReflect() protoreflect.Message {
	mi := &file_handler_LLOneBot_protos_handler_define_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageChain_Video.ProtoReflect.Descriptor instead.
func (*MessageChain_Video) Descriptor() ([]byte, []int) {
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP(), []int{4}
}

func (x *MessageChain_Video) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type MessageChain_At struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetId string `protobuf:"bytes,1,opt,name=TargetId,proto3" json:"TargetId,omitempty"`
}

func (x *MessageChain_At) Reset() {
	*x = MessageChain_At{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handler_LLOneBot_protos_handler_define_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageChain_At) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageChain_At) ProtoMessage() {}

func (x *MessageChain_At) ProtoReflect() protoreflect.Message {
	mi := &file_handler_LLOneBot_protos_handler_define_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageChain_At.ProtoReflect.Descriptor instead.
func (*MessageChain_At) Descriptor() ([]byte, []int) {
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP(), []int{5}
}

func (x *MessageChain_At) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type MessageChain_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId string `protobuf:"bytes,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
}

func (x *MessageChain_Reply) Reset() {
	*x = MessageChain_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handler_LLOneBot_protos_handler_define_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageChain_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageChain_Reply) ProtoMessage() {}

func (x *MessageChain_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_handler_LLOneBot_protos_handler_define_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageChain_Reply.ProtoReflect.Descriptor instead.
func (*MessageChain_Reply) Descriptor() ([]byte, []int) {
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP(), []int{6}
}

func (x *MessageChain_Reply) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

var File_handler_LLOneBot_protos_handler_define_proto protoreflect.FileDescriptor

var file_handler_LLOneBot_protos_handler_define_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2f, 0x4c, 0x4c, 0x4f, 0x6e, 0x65, 0x42,
	0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x72, 0x2f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x22, 0xc6, 0x03, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x31, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x64, 0x65,
	0x66, 0x69, 0x6e, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x32, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x5f, 0x54, 0x65, 0x78, 0x74, 0x48, 0x01, 0x52, 0x04, 0x54, 0x65, 0x78,
	0x74, 0x88, 0x01, 0x01, 0x12, 0x35, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x48,
	0x02, 0x52, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x35, 0x0a, 0x05, 0x56,
	0x6f, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x5f, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x48, 0x03, 0x52, 0x05, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x35, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x48, 0x04, 0x52,
	0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x88, 0x01, 0x01, 0x12, 0x2c, 0x0a, 0x02, 0x41, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x41, 0x74, 0x48, 0x05,
	0x52, 0x02, 0x41, 0x74, 0x88, 0x01, 0x01, 0x12, 0x35, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x48, 0x06, 0x52, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x88, 0x01, 0x01, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x54, 0x79, 0x70, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x54, 0x65, 0x78, 0x74,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x56,
	0x6f, 0x69, 0x63, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x05,
	0x0a, 0x03, 0x5f, 0x41, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x27, 0x0a, 0x11, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x5f,
	0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x54, 0x65, 0x78, 0x74, 0x22, 0x26, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c,
	0x22, 0x26, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x5f, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x22, 0x26, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x10,
	0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c,
	0x22, 0x2d, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x5f, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x22,
	0x32, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x5f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x2a, 0x78, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x5f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x10, 0x00, 0x12, 0x18, 0x0a,
	0x14, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x51, 0x51,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x43, 0x6d, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x5f, 0x42, 0x6f, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x10, 0x03, 0x2a, 0x3d, 0x0a,
	0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x10, 0x01, 0x2a, 0xb6, 0x01, 0x0a,
	0x10, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x19, 0x0a, 0x15, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x54, 0x65, 0x78, 0x74, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x5f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x56, 0x6f, 0x69,
	0x63, 0x65, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x10, 0x03,
	0x12, 0x17, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x41, 0x74, 0x10, 0x04, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x10, 0x05, 0x2a, 0x9b, 0x01, 0x0a, 0x0b, 0x51, 0x51, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x51, 0x51, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x64, 0x64, 0x10, 0x00, 0x12,
	0x1b, 0x0a, 0x17, 0x51, 0x51, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15,
	0x51, 0x51, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4d, 0x75, 0x74, 0x65, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x51, 0x51, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x55, 0x6e, 0x6d, 0x75,
	0x74, 0x65, 0x10, 0x03, 0x12, 0x1d, 0x0a, 0x19, 0x51, 0x51, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x5f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x63, 0x61, 0x6c,
	0x6c, 0x10, 0x04, 0x2a, 0x64, 0x0a, 0x18, 0x51, 0x51, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x5f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x64, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x23, 0x0a, 0x1f, 0x51, 0x51, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x41, 0x64, 0x64, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x10, 0x00, 0x12, 0x23, 0x0a, 0x1f, 0x51, 0x51, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x5f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x64, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x5f, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x10, 0x01, 0x2a, 0x6b, 0x0a, 0x1b, 0x51, 0x51, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x22, 0x51, 0x51, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x10, 0x00,
	0x12, 0x24, 0x0a, 0x20, 0x51, 0x51, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f,
	0x4b, 0x69, 0x63, 0x6b, 0x10, 0x01, 0x2a, 0x73, 0x0a, 0x1d, 0x51, 0x51, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x63,
	0x61, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x23, 0x51, 0x51, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x63, 0x61, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x10, 0x00,
	0x12, 0x29, 0x0a, 0x25, 0x51, 0x51, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x54, 0x79, 0x70,
	0x65, 0x5f, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x10, 0x01, 0x2a, 0xaf, 0x01, 0x0a, 0x0c,
	0x43, 0x6d, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x19,
	0x43, 0x6d, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x47, 0x65, 0x74,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x10, 0x00, 0x12, 0x23, 0x0a, 0x1f, 0x43,
	0x6d, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x47, 0x65, 0x74, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x10, 0x01,
	0x12, 0x1b, 0x0a, 0x17, 0x43, 0x6d, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x5f, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x10, 0x02, 0x12, 0x1e, 0x0a,
	0x1a, 0x43, 0x6d, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x47, 0x65,
	0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x10, 0x03, 0x12, 0x1e, 0x0a,
	0x1a, 0x43, 0x6d, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x47, 0x65,
	0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x10, 0x04, 0x2a, 0x48, 0x0a,
	0x0c, 0x42, 0x6f, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a,
	0x18, 0x42, 0x6f, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x42,
	0x6f, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x10, 0x01, 0x2a, 0x4b, 0x0a, 0x09, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x6f, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x6f, 0x6c,
	0x65, 0x5f, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x6f, 0x6c, 0x65, 0x5f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x10, 0x01, 0x12,
	0x13, 0x0a, 0x0f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x6f, 0x6c, 0x65, 0x5f, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x10, 0x02, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x6e, 0x61, 0x63, 0x68, 0x69, 0x2d, 0x73, 0x68, 0x2f, 0x73, 0x75,
	0x73, 0x75, 0x62, 0x6f, 0x74, 0x2d, 0x63, 0x6f, 0x64, 0x65, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x72, 0x2f, 0x4c, 0x4c, 0x4f, 0x6e, 0x65, 0x42, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_handler_LLOneBot_protos_handler_define_proto_rawDescOnce sync.Once
	file_handler_LLOneBot_protos_handler_define_proto_rawDescData = file_handler_LLOneBot_protos_handler_define_proto_rawDesc
)

func file_handler_LLOneBot_protos_handler_define_proto_rawDescGZIP() []byte {
	file_handler_LLOneBot_protos_handler_define_proto_rawDescOnce.Do(func() {
		file_handler_LLOneBot_protos_handler_define_proto_rawDescData = protoimpl.X.CompressGZIP(file_handler_LLOneBot_protos_handler_define_proto_rawDescData)
	})
	return file_handler_LLOneBot_protos_handler_define_proto_rawDescData
}

var file_handler_LLOneBot_protos_handler_define_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_handler_LLOneBot_protos_handler_define_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_handler_LLOneBot_protos_handler_define_proto_goTypes = []any{
	(ResponseType)(0),                  // 0: define.ResponseType
	(MessageType)(0),                   // 1: define.MessageType
	(MessageChainType)(0),              // 2: define.MessageChainType
	(QQEventType)(0),                   // 3: define.QQEventType
	(QQEventType_GroupAddType)(0),      // 4: define.QQEventType_GroupAddType
	(QQEventType_GroupRemoveType)(0),   // 5: define.QQEventType_GroupRemoveType
	(QQEventType_MessageRecallType)(0), // 6: define.QQEventType_MessageRecallType
	(CmdEventType)(0),                  // 7: define.CmdEventType
	(BotEventType)(0),                  // 8: define.BotEventType
	(GroupRole)(0),                     // 9: define.GroupRole
	(*MessageChainObject)(nil),         // 10: define.MessageChainObject
	(*MessageChain_Text)(nil),          // 11: define.MessageChain_Text
	(*MessageChain_Image)(nil),         // 12: define.MessageChain_Image
	(*MessageChain_Voice)(nil),         // 13: define.MessageChain_Voice
	(*MessageChain_Video)(nil),         // 14: define.MessageChain_Video
	(*MessageChain_At)(nil),            // 15: define.MessageChain_At
	(*MessageChain_Reply)(nil),         // 16: define.MessageChain_Reply
}
var file_handler_LLOneBot_protos_handler_define_proto_depIdxs = []int32{
	2,  // 0: define.MessageChainObject.Type:type_name -> define.MessageChainType
	11, // 1: define.MessageChainObject.Text:type_name -> define.MessageChain_Text
	12, // 2: define.MessageChainObject.Image:type_name -> define.MessageChain_Image
	13, // 3: define.MessageChainObject.Voice:type_name -> define.MessageChain_Voice
	14, // 4: define.MessageChainObject.Video:type_name -> define.MessageChain_Video
	15, // 5: define.MessageChainObject.At:type_name -> define.MessageChain_At
	16, // 6: define.MessageChainObject.Reply:type_name -> define.MessageChain_Reply
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_handler_LLOneBot_protos_handler_define_proto_init() }
func file_handler_LLOneBot_protos_handler_define_proto_init() {
	if File_handler_LLOneBot_protos_handler_define_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_handler_LLOneBot_protos_handler_define_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MessageChainObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_handler_LLOneBot_protos_handler_define_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MessageChain_Text); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_handler_LLOneBot_protos_handler_define_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MessageChain_Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_handler_LLOneBot_protos_handler_define_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*MessageChain_Voice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_handler_LLOneBot_protos_handler_define_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*MessageChain_Video); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_handler_LLOneBot_protos_handler_define_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*MessageChain_At); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_handler_LLOneBot_protos_handler_define_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*MessageChain_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_handler_LLOneBot_protos_handler_define_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_handler_LLOneBot_protos_handler_define_proto_rawDesc,
			NumEnums:      10,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_handler_LLOneBot_protos_handler_define_proto_goTypes,
		DependencyIndexes: file_handler_LLOneBot_protos_handler_define_proto_depIdxs,
		EnumInfos:         file_handler_LLOneBot_protos_handler_define_proto_enumTypes,
		MessageInfos:      file_handler_LLOneBot_protos_handler_define_proto_msgTypes,
	}.Build()
	File_handler_LLOneBot_protos_handler_define_proto = out.File
	file_handler_LLOneBot_protos_handler_define_proto_rawDesc = nil
	file_handler_LLOneBot_protos_handler_define_proto_goTypes = nil
	file_handler_LLOneBot_protos_handler_define_proto_depIdxs = nil
}
