// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: handler/LLOneBot/protos/handler/request/request.proto

package request

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RequestHandler_BotRequestMarshal_FullMethodName = "/RequestHandler/BotRequestMarshal"
)

// RequestHandlerClient is the client API for RequestHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RequestHandlerClient interface {
	BotRequestMarshal(ctx context.Context, in *BotRequestMarshalRequest, opts ...grpc.CallOption) (*BotRequestMarshalResponse, error)
}

type requestHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewRequestHandlerClient(cc grpc.ClientConnInterface) RequestHandlerClient {
	return &requestHandlerClient{cc}
}

func (c *requestHandlerClient) BotRequestMarshal(ctx context.Context, in *BotRequestMarshalRequest, opts ...grpc.CallOption) (*BotRequestMarshalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotRequestMarshalResponse)
	err := c.cc.Invoke(ctx, RequestHandler_BotRequestMarshal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequestHandlerServer is the server API for RequestHandler service.
// All implementations must embed UnimplementedRequestHandlerServer
// for forward compatibility.
type RequestHandlerServer interface {
	BotRequestMarshal(context.Context, *BotRequestMarshalRequest) (*BotRequestMarshalResponse, error)
	mustEmbedUnimplementedRequestHandlerServer()
}

// UnimplementedRequestHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRequestHandlerServer struct{}

func (UnimplementedRequestHandlerServer) BotRequestMarshal(context.Context, *BotRequestMarshalRequest) (*BotRequestMarshalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BotRequestMarshal not implemented")
}
func (UnimplementedRequestHandlerServer) mustEmbedUnimplementedRequestHandlerServer() {}
func (UnimplementedRequestHandlerServer) testEmbeddedByValue()                        {}

// UnsafeRequestHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RequestHandlerServer will
// result in compilation errors.
type UnsafeRequestHandlerServer interface {
	mustEmbedUnimplementedRequestHandlerServer()
}

func RegisterRequestHandlerServer(s grpc.ServiceRegistrar, srv RequestHandlerServer) {
	// If the following call pancis, it indicates UnimplementedRequestHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RequestHandler_ServiceDesc, srv)
}

func _RequestHandler_BotRequestMarshal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotRequestMarshalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestHandlerServer).BotRequestMarshal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestHandler_BotRequestMarshal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestHandlerServer).BotRequestMarshal(ctx, req.(*BotRequestMarshalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RequestHandler_ServiceDesc is the grpc.ServiceDesc for RequestHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RequestHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RequestHandler",
	HandlerType: (*RequestHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BotRequestMarshal",
			Handler:    _RequestHandler_BotRequestMarshal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "handler/LLOneBot/protos/handler/request/request.proto",
}
