// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: plugin/uno/protos/uno/uno.proto

package uno

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stage int32

const (
	Stage_WaitingStart   Stage = 0
	Stage_ElectingBanker Stage = 1
	Stage_SendingCard    Stage = 2
)

// Enum value maps for Stage.
var (
	Stage_name = map[int32]string{
		0: "WaitingStart",
		1: "ElectingBanker",
		2: "SendingCard",
	}
	Stage_value = map[string]int32{
		"WaitingStart":   0,
		"ElectingBanker": 1,
		"SendingCard":    2,
	}
)

func (x Stage) Enum() *Stage {
	p := new(Stage)
	*p = x
	return p
}

func (x Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_uno_protos_uno_uno_proto_enumTypes[0].Descriptor()
}

func (Stage) Type() protoreflect.EnumType {
	return &file_plugin_uno_protos_uno_uno_proto_enumTypes[0]
}

func (x Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stage.Descriptor instead.
func (Stage) EnumDescriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{0}
}

type Errors int32

const (
	Errors_Unexpected         Errors = 0 //意外错误
	Errors_RoomStarted        Errors = 1 //房间已开始游戏
	Errors_RoomFull           Errors = 2 //房间已满
	Errors_RoomExistPlayer    Errors = 3 //玩家已存在房间内
	Errors_RoomNoReachPlayers Errors = 4 //玩家数未达到
	Errors_RoomNoExistPlayer  Errors = 5 //玩家不存在房间内
)

// Enum value maps for Errors.
var (
	Errors_name = map[int32]string{
		0: "Unexpected",
		1: "RoomStarted",
		2: "RoomFull",
		3: "RoomExistPlayer",
		4: "RoomNoReachPlayers",
		5: "RoomNoExistPlayer",
	}
	Errors_value = map[string]int32{
		"Unexpected":         0,
		"RoomStarted":        1,
		"RoomFull":           2,
		"RoomExistPlayer":    3,
		"RoomNoReachPlayers": 4,
		"RoomNoExistPlayer":  5,
	}
)

func (x Errors) Enum() *Errors {
	p := new(Errors)
	*p = x
	return p
}

func (x Errors) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Errors) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_uno_protos_uno_uno_proto_enumTypes[1].Descriptor()
}

func (Errors) Type() protoreflect.EnumType {
	return &file_plugin_uno_protos_uno_uno_proto_enumTypes[1]
}

func (x Errors) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Errors.Descriptor instead.
func (Errors) EnumDescriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{1}
}

type CardColor int32

const (
	CardColor_Blue   CardColor = 0
	CardColor_Yellow CardColor = 1
	CardColor_Red    CardColor = 2
	CardColor_Green  CardColor = 3
	CardColor_Black  CardColor = 4
)

// Enum value maps for CardColor.
var (
	CardColor_name = map[int32]string{
		0: "Blue",
		1: "Yellow",
		2: "Red",
		3: "Green",
		4: "Black",
	}
	CardColor_value = map[string]int32{
		"Blue":   0,
		"Yellow": 1,
		"Red":    2,
		"Green":  3,
		"Black":  4,
	}
)

func (x CardColor) Enum() *CardColor {
	p := new(CardColor)
	*p = x
	return p
}

func (x CardColor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardColor) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_uno_protos_uno_uno_proto_enumTypes[2].Descriptor()
}

func (CardColor) Type() protoreflect.EnumType {
	return &file_plugin_uno_protos_uno_uno_proto_enumTypes[2]
}

func (x CardColor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardColor.Descriptor instead.
func (CardColor) EnumDescriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{2}
}

type CardNumber int32

const (
	CardNumber_Zero  CardNumber = 0
	CardNumber_One   CardNumber = 1
	CardNumber_Two   CardNumber = 2
	CardNumber_Three CardNumber = 3
	CardNumber_Four  CardNumber = 4
	CardNumber_Five  CardNumber = 5
	CardNumber_Six   CardNumber = 6
	CardNumber_Seven CardNumber = 7
	CardNumber_Eight CardNumber = 8
	CardNumber_Nine  CardNumber = 9
)

// Enum value maps for CardNumber.
var (
	CardNumber_name = map[int32]string{
		0: "Zero",
		1: "One",
		2: "Two",
		3: "Three",
		4: "Four",
		5: "Five",
		6: "Six",
		7: "Seven",
		8: "Eight",
		9: "Nine",
	}
	CardNumber_value = map[string]int32{
		"Zero":  0,
		"One":   1,
		"Two":   2,
		"Three": 3,
		"Four":  4,
		"Five":  5,
		"Six":   6,
		"Seven": 7,
		"Eight": 8,
		"Nine":  9,
	}
)

func (x CardNumber) Enum() *CardNumber {
	p := new(CardNumber)
	*p = x
	return p
}

func (x CardNumber) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardNumber) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_uno_protos_uno_uno_proto_enumTypes[3].Descriptor()
}

func (CardNumber) Type() protoreflect.EnumType {
	return &file_plugin_uno_protos_uno_uno_proto_enumTypes[3]
}

func (x CardNumber) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardNumber.Descriptor instead.
func (CardNumber) EnumDescriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{3}
}

type FeatureCards int32

const (
	FeatureCards_Skip         FeatureCards = 0
	FeatureCards_Reverse      FeatureCards = 1
	FeatureCards_DrawTwo      FeatureCards = 2
	FeatureCards_Wild         FeatureCards = 3
	FeatureCards_WildDrawFour FeatureCards = 4
)

// Enum value maps for FeatureCards.
var (
	FeatureCards_name = map[int32]string{
		0: "Skip",
		1: "Reverse",
		2: "DrawTwo",
		3: "Wild",
		4: "WildDrawFour",
	}
	FeatureCards_value = map[string]int32{
		"Skip":         0,
		"Reverse":      1,
		"DrawTwo":      2,
		"Wild":         3,
		"WildDrawFour": 4,
	}
)

func (x FeatureCards) Enum() *FeatureCards {
	p := new(FeatureCards)
	*p = x
	return p
}

func (x FeatureCards) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeatureCards) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_uno_protos_uno_uno_proto_enumTypes[4].Descriptor()
}

func (FeatureCards) Type() protoreflect.EnumType {
	return &file_plugin_uno_protos_uno_uno_proto_enumTypes[4]
}

func (x FeatureCards) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeatureCards.Descriptor instead.
func (FeatureCards) EnumDescriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{4}
}

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NormalCard  *NormalCard  `protobuf:"bytes,1,opt,name=NormalCard,proto3,oneof" json:"NormalCard,omitempty"`
	FeatureCard *FeatureCard `protobuf:"bytes,2,opt,name=FeatureCard,proto3,oneof" json:"FeatureCard,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetNormalCard() *NormalCard {
	if x != nil {
		return x.NormalCard
	}
	return nil
}

func (x *Card) GetFeatureCard() *FeatureCard {
	if x != nil {
		return x.FeatureCard
	}
	return nil
}

type NormalCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color  CardColor  `protobuf:"varint,1,opt,name=Color,proto3,enum=susubot.plugin.uno.CardColor" json:"Color,omitempty"`
	Number CardNumber `protobuf:"varint,2,opt,name=Number,proto3,enum=susubot.plugin.uno.CardNumber" json:"Number,omitempty"`
}

func (x *NormalCard) Reset() {
	*x = NormalCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NormalCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalCard) ProtoMessage() {}

func (x *NormalCard) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalCard.ProtoReflect.Descriptor instead.
func (*NormalCard) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{1}
}

func (x *NormalCard) GetColor() CardColor {
	if x != nil {
		return x.Color
	}
	return CardColor_Blue
}

func (x *NormalCard) GetNumber() CardNumber {
	if x != nil {
		return x.Number
	}
	return CardNumber_Zero
}

type FeatureCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color       CardColor    `protobuf:"varint,1,opt,name=Color,proto3,enum=susubot.plugin.uno.CardColor" json:"Color,omitempty"`
	FeatureCard FeatureCards `protobuf:"varint,2,opt,name=FeatureCard,proto3,enum=susubot.plugin.uno.FeatureCards" json:"FeatureCard,omitempty"`
}

func (x *FeatureCard) Reset() {
	*x = FeatureCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureCard) ProtoMessage() {}

func (x *FeatureCard) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureCard.ProtoReflect.Descriptor instead.
func (*FeatureCard) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{2}
}

func (x *FeatureCard) GetColor() CardColor {
	if x != nil {
		return x.Color
	}
	return CardColor_Blue
}

func (x *FeatureCard) GetFeatureCard() FeatureCards {
	if x != nil {
		return x.FeatureCard
	}
	return FeatureCards_Skip
}

type PlayerAccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *PlayerAccountInfo) Reset() {
	*x = PlayerAccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerAccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAccountInfo) ProtoMessage() {}

func (x *PlayerAccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAccountInfo.ProtoReflect.Descriptor instead.
func (*PlayerAccountInfo) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerAccountInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerAccountInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PlayerRoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomHash string `protobuf:"bytes,1,opt,name=RoomHash,proto3" json:"RoomHash,omitempty"`
}

func (x *PlayerRoomInfo) Reset() {
	*x = PlayerRoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerRoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRoomInfo) ProtoMessage() {}

func (x *PlayerRoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRoomInfo.ProtoReflect.Descriptor instead.
func (*PlayerRoomInfo) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerRoomInfo) GetRoomHash() string {
	if x != nil {
		return x.RoomHash
	}
	return ""
}

type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerAccountInfo *PlayerAccountInfo `protobuf:"bytes,1,opt,name=PlayerAccountInfo,proto3" json:"PlayerAccountInfo,omitempty"`
	PlayerRoomInfo    *PlayerRoomInfo    `protobuf:"bytes,2,opt,name=PlayerRoomInfo,proto3,oneof" json:"PlayerRoomInfo,omitempty"`
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerInfo) GetPlayerAccountInfo() *PlayerAccountInfo {
	if x != nil {
		return x.PlayerAccountInfo
	}
	return nil
}

func (x *PlayerInfo) GetPlayerRoomInfo() *PlayerRoomInfo {
	if x != nil {
		return x.PlayerRoomInfo
	}
	return nil
}

type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash  string `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Stage Stage  `protobuf:"varint,2,opt,name=Stage,proto3,enum=susubot.plugin.uno.Stage" json:"Stage,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{6}
}

func (x *Room) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Room) GetStage() Stage {
	if x != nil {
		return x.Stage
	}
	return Stage_WaitingStart
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{7}
}

type BasicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err *Errors `protobuf:"varint,1,opt,name=err,proto3,enum=susubot.plugin.uno.Errors,oneof" json:"err,omitempty"`
}

func (x *BasicResponse) Reset() {
	*x = BasicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicResponse) ProtoMessage() {}

func (x *BasicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicResponse.ProtoReflect.Descriptor instead.
func (*BasicResponse) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{8}
}

func (x *BasicResponse) GetErr() Errors {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return Errors_Unexpected
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomHash string `protobuf:"bytes,1,opt,name=RoomHash,proto3" json:"RoomHash,omitempty"`
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{9}
}

func (x *CreateRoomResponse) GetRoomHash() string {
	if x != nil {
		return x.RoomHash
	}
	return ""
}

type GetRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomHash string `protobuf:"bytes,1,opt,name=RoomHash,proto3" json:"RoomHash,omitempty"`
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{10}
}

func (x *GetRoomRequest) GetRoomHash() string {
	if x != nil {
		return x.RoomHash
	}
	return ""
}

type GetRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *Room `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
}

func (x *GetRoomResponse) Reset() {
	*x = GetRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResponse) ProtoMessage() {}

func (x *GetRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResponse) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{11}
}

func (x *GetRoomResponse) GetInfo() *Room {
	if x != nil {
		return x.Info
	}
	return nil
}

type GetRoomsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*Room `protobuf:"bytes,1,rep,name=Infos,proto3" json:"Infos,omitempty"`
}

func (x *GetRoomsResponse) Reset() {
	*x = GetRoomsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsResponse) ProtoMessage() {}

func (x *GetRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsResponse.ProtoReflect.Descriptor instead.
func (*GetRoomsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{12}
}

func (x *GetRoomsResponse) GetInfos() []*Room {
	if x != nil {
		return x.Infos
	}
	return nil
}

type JoinRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId   string `protobuf:"bytes,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	PlayerName string `protobuf:"bytes,2,opt,name=PlayerName,proto3" json:"PlayerName,omitempty"`
	RoomHash   string `protobuf:"bytes,3,opt,name=RoomHash,proto3" json:"RoomHash,omitempty"`
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{13}
}

func (x *JoinRoomRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *JoinRoomRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *JoinRoomRequest) GetRoomHash() string {
	if x != nil {
		return x.RoomHash
	}
	return ""
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err     *Errors              `protobuf:"varint,1,opt,name=err,proto3,enum=susubot.plugin.uno.Errors,oneof" json:"err,omitempty"`
	Players []*PlayerAccountInfo `protobuf:"bytes,2,rep,name=Players,proto3" json:"Players,omitempty"`
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{14}
}

func (x *JoinRoomResponse) GetErr() Errors {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return Errors_Unexpected
}

func (x *JoinRoomResponse) GetPlayers() []*PlayerAccountInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

type ExitRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
}

func (x *ExitRoomRequest) Reset() {
	*x = ExitRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExitRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitRoomRequest) ProtoMessage() {}

func (x *ExitRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitRoomRequest.ProtoReflect.Descriptor instead.
func (*ExitRoomRequest) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{15}
}

func (x *ExitRoomRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type ExitRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err     *Errors              `protobuf:"varint,1,opt,name=err,proto3,enum=susubot.plugin.uno.Errors,oneof" json:"err,omitempty"`
	Players []*PlayerAccountInfo `protobuf:"bytes,2,rep,name=Players,proto3" json:"Players,omitempty"`
}

func (x *ExitRoomResponse) Reset() {
	*x = ExitRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExitRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitRoomResponse) ProtoMessage() {}

func (x *ExitRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitRoomResponse.ProtoReflect.Descriptor instead.
func (*ExitRoomResponse) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{16}
}

func (x *ExitRoomResponse) GetErr() Errors {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return Errors_Unexpected
}

func (x *ExitRoomResponse) GetPlayers() []*PlayerAccountInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

type StartRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId *string `protobuf:"bytes,1,opt,name=PlayerId,proto3,oneof" json:"PlayerId,omitempty"`
	RoomHash *string `protobuf:"bytes,2,opt,name=RoomHash,proto3,oneof" json:"RoomHash,omitempty"`
}

func (x *StartRoomRequest) Reset() {
	*x = StartRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRoomRequest) ProtoMessage() {}

func (x *StartRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRoomRequest.ProtoReflect.Descriptor instead.
func (*StartRoomRequest) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{17}
}

func (x *StartRoomRequest) GetPlayerId() string {
	if x != nil && x.PlayerId != nil {
		return *x.PlayerId
	}
	return ""
}

func (x *StartRoomRequest) GetRoomHash() string {
	if x != nil && x.RoomHash != nil {
		return *x.RoomHash
	}
	return ""
}

type DrawCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
}

func (x *DrawCardRequest) Reset() {
	*x = DrawCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrawCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawCardRequest) ProtoMessage() {}

func (x *DrawCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawCardRequest.ProtoReflect.Descriptor instead.
func (*DrawCardRequest) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{18}
}

func (x *DrawCardRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type DrawCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err *Errors `protobuf:"varint,1,opt,name=err,proto3,enum=susubot.plugin.uno.Errors,oneof" json:"err,omitempty"`
}

func (x *DrawCardResponse) Reset() {
	*x = DrawCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrawCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawCardResponse) ProtoMessage() {}

func (x *DrawCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawCardResponse.ProtoReflect.Descriptor instead.
func (*DrawCardResponse) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{19}
}

func (x *DrawCardResponse) GetErr() Errors {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return Errors_Unexpected
}

type SendCardActionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId  string  `protobuf:"bytes,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	SendCards []*Card `protobuf:"bytes,2,rep,name=SendCards,proto3" json:"SendCards,omitempty"`
}

func (x *SendCardActionRequest) Reset() {
	*x = SendCardActionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCardActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCardActionRequest) ProtoMessage() {}

func (x *SendCardActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCardActionRequest.ProtoReflect.Descriptor instead.
func (*SendCardActionRequest) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{20}
}

func (x *SendCardActionRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *SendCardActionRequest) GetSendCards() []*Card {
	if x != nil {
		return x.SendCards
	}
	return nil
}

type SendCardActionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err          *Errors     `protobuf:"varint,1,opt,name=err,proto3,enum=susubot.plugin.uno.Errors,oneof" json:"err,omitempty"`
	NextOperator *PlayerInfo `protobuf:"bytes,2,opt,name=NextOperator,proto3" json:"NextOperator,omitempty"`
}

func (x *SendCardActionResponse) Reset() {
	*x = SendCardActionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCardActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCardActionResponse) ProtoMessage() {}

func (x *SendCardActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_uno_protos_uno_uno_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCardActionResponse.ProtoReflect.Descriptor instead.
func (*SendCardActionResponse) Descriptor() ([]byte, []int) {
	return file_plugin_uno_protos_uno_uno_proto_rawDescGZIP(), []int{21}
}

func (x *SendCardActionResponse) GetErr() Errors {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return Errors_Unexpected
}

func (x *SendCardActionResponse) GetNextOperator() *PlayerInfo {
	if x != nil {
		return x.NextOperator
	}
	return nil
}

var File_plugin_uno_protos_uno_uno_proto protoreflect.FileDescriptor

var file_plugin_uno_protos_uno_uno_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x75, 0x6e, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2f, 0x75, 0x6e, 0x6f, 0x2f, 0x75, 0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x22, 0xb2, 0x01, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x43,
	0x0a, 0x0a, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x43, 0x61,
	0x72, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x43, 0x61, 0x72, 0x64,
	0x88, 0x01, 0x01, 0x12, 0x46, 0x0a, 0x0b, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x61,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62,
	0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x46, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x61, 0x72, 0x64, 0x48, 0x01, 0x52, 0x0b, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x43, 0x61, 0x72, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f,
	0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x61, 0x72, 0x64, 0x22, 0x79, 0x0a, 0x0a, 0x4e, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x12, 0x33, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f,
	0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x43, 0x61, 0x72,
	0x64, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x36, 0x0a,
	0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e,
	0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75,
	0x6e, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x86, 0x01, 0x0a, 0x0b, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x43, 0x61, 0x72, 0x64, 0x12, 0x33, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x52, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x42, 0x0a, 0x0b, 0x46, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x20, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x61, 0x72, 0x64,
	0x73, 0x52, 0x0b, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x61, 0x72, 0x64, 0x22, 0x37,
	0x0a, 0x11, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6f,
	0x6d, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x6f, 0x6f,
	0x6d, 0x48, 0x61, 0x73, 0x68, 0x22, 0xc5, 0x01, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x53, 0x0a, 0x11, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x11, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x4f, 0x0a, 0x0e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x88, 0x01, 0x01, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x4b, 0x0a,
	0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2f, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62,
	0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x52, 0x05, 0x53, 0x74, 0x61, 0x67, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x4a, 0x0a, 0x0d, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1a, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x48, 0x00, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x65, 0x72, 0x72, 0x22,
	0x30, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x48, 0x61, 0x73,
	0x68, 0x22, 0x2c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x48, 0x61, 0x73, 0x68, 0x22,
	0x3f, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x42, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x05, 0x49,
	0x6e, 0x66, 0x6f, 0x73, 0x22, 0x69, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x48, 0x61, 0x73, 0x68, 0x22,
	0x8e, 0x01, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1a, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x48, 0x00, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x88, 0x01, 0x01, 0x12, 0x3f, 0x0a, 0x07, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62,
	0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x07, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x65, 0x72, 0x72,
	0x22, 0x2d, 0x0a, 0x0f, 0x45, 0x78, 0x69, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x8e, 0x01, 0x0a, 0x10, 0x45, 0x78, 0x69, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1a, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x48, 0x00, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x88, 0x01, 0x01, 0x12, 0x3f, 0x0a, 0x07, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62,
	0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x07, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x65, 0x72, 0x72,
	0x22, 0x6e, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x48,
	0x61, 0x73, 0x68, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x52, 0x6f, 0x6f, 0x6d, 0x48, 0x61, 0x73, 0x68,
	0x22, 0x2d, 0x0a, 0x0f, 0x44, 0x72, 0x61, 0x77, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x4d, 0x0a, 0x10, 0x44, 0x72, 0x61, 0x77, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1a, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x48, 0x00, 0x52, 0x03,
	0x65, 0x72, 0x72, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x65, 0x72, 0x72, 0x22, 0x6b,
	0x0a, 0x15, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x73, 0x22, 0x97, 0x01, 0x0a, 0x16,
	0x53, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x48,
	0x00, 0x52, 0x03, 0x65, 0x72, 0x72, 0x88, 0x01, 0x01, 0x12, 0x42, 0x0a, 0x0c, 0x4e, 0x65, 0x78,
	0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0c, 0x4e, 0x65, 0x78, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x42, 0x06, 0x0a,
	0x04, 0x5f, 0x65, 0x72, 0x72, 0x2a, 0x3e, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x10,
	0x0a, 0x0c, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x72, 0x74, 0x10, 0x00,
	0x12, 0x12, 0x0a, 0x0e, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x6e, 0x6b,
	0x65, 0x72, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x43,
	0x61, 0x72, 0x64, 0x10, 0x02, 0x2a, 0x7b, 0x0a, 0x06, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12,
	0x0e, 0x0a, 0x0a, 0x55, 0x6e, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x10, 0x01,
	0x12, 0x0c, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x46, 0x75, 0x6c, 0x6c, 0x10, 0x02, 0x12, 0x13,
	0x0a, 0x0f, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x78, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x6f, 0x52, 0x65, 0x61,
	0x63, 0x68, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x52,
	0x6f, 0x6f, 0x6d, 0x4e, 0x6f, 0x45, 0x78, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x10, 0x05, 0x2a, 0x40, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12,
	0x08, 0x0a, 0x04, 0x42, 0x6c, 0x75, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x59, 0x65, 0x6c,
	0x6c, 0x6f, 0x77, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x65, 0x64, 0x10, 0x02, 0x12, 0x09,
	0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x6e, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x6c, 0x61,
	0x63, 0x6b, 0x10, 0x04, 0x2a, 0x70, 0x0a, 0x0a, 0x43, 0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x08, 0x0a, 0x04, 0x5a, 0x65, 0x72, 0x6f, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x4f, 0x6e, 0x65, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x77, 0x6f, 0x10, 0x02, 0x12, 0x09,
	0x0a, 0x05, 0x54, 0x68, 0x72, 0x65, 0x65, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x6f, 0x75,
	0x72, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x69, 0x76, 0x65, 0x10, 0x05, 0x12, 0x07, 0x0a,
	0x03, 0x53, 0x69, 0x78, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x65, 0x76, 0x65, 0x6e, 0x10,
	0x07, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x69, 0x67, 0x68, 0x74, 0x10, 0x08, 0x12, 0x08, 0x0a, 0x04,
	0x4e, 0x69, 0x6e, 0x65, 0x10, 0x09, 0x2a, 0x4e, 0x0a, 0x0c, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x6b, 0x69, 0x70, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x10, 0x01, 0x12, 0x0b, 0x0a,
	0x07, 0x44, 0x72, 0x61, 0x77, 0x54, 0x77, 0x6f, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x69,
	0x6c, 0x64, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x57, 0x69, 0x6c, 0x64, 0x44, 0x72, 0x61, 0x77,
	0x46, 0x6f, 0x75, 0x72, 0x10, 0x04, 0x32, 0xbb, 0x05, 0x0a, 0x03, 0x75, 0x6e, 0x6f, 0x12, 0x4f,
	0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x19, 0x2e, 0x73,
	0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e,
	0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x26, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f,
	0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4b, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x19, 0x2e, 0x73, 0x75,
	0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x24, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x22, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f,
	0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x75,
	0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x55, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x23, 0x2e, 0x73,
	0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e,
	0x6f, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x08, 0x45, 0x78, 0x69, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x12, 0x23, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x45, 0x78, 0x69, 0x74, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62,
	0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x45, 0x78,
	0x69, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54,
	0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x24, 0x2e, 0x73, 0x75,
	0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x08, 0x44, 0x72, 0x61, 0x77, 0x43, 0x61, 0x72, 0x64,
	0x12, 0x23, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x44, 0x72, 0x61, 0x77, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x44, 0x72, 0x61, 0x77, 0x43,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x67, 0x0a, 0x0e, 0x53,
	0x65, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x2e,
	0x73, 0x75, 0x73, 0x75, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75,
	0x6e, 0x6f, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x73, 0x75, 0x73, 0x75, 0x62,
	0x6f, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x75, 0x6e, 0x6f, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x75,
	0x6e, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plugin_uno_protos_uno_uno_proto_rawDescOnce sync.Once
	file_plugin_uno_protos_uno_uno_proto_rawDescData = file_plugin_uno_protos_uno_uno_proto_rawDesc
)

func file_plugin_uno_protos_uno_uno_proto_rawDescGZIP() []byte {
	file_plugin_uno_protos_uno_uno_proto_rawDescOnce.Do(func() {
		file_plugin_uno_protos_uno_uno_proto_rawDescData = protoimpl.X.CompressGZIP(file_plugin_uno_protos_uno_uno_proto_rawDescData)
	})
	return file_plugin_uno_protos_uno_uno_proto_rawDescData
}

var file_plugin_uno_protos_uno_uno_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_plugin_uno_protos_uno_uno_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_plugin_uno_protos_uno_uno_proto_goTypes = []any{
	(Stage)(0),                     // 0: susubot.plugin.uno.Stage
	(Errors)(0),                    // 1: susubot.plugin.uno.Errors
	(CardColor)(0),                 // 2: susubot.plugin.uno.CardColor
	(CardNumber)(0),                // 3: susubot.plugin.uno.CardNumber
	(FeatureCards)(0),              // 4: susubot.plugin.uno.FeatureCards
	(*Card)(nil),                   // 5: susubot.plugin.uno.Card
	(*NormalCard)(nil),             // 6: susubot.plugin.uno.NormalCard
	(*FeatureCard)(nil),            // 7: susubot.plugin.uno.FeatureCard
	(*PlayerAccountInfo)(nil),      // 8: susubot.plugin.uno.PlayerAccountInfo
	(*PlayerRoomInfo)(nil),         // 9: susubot.plugin.uno.PlayerRoomInfo
	(*PlayerInfo)(nil),             // 10: susubot.plugin.uno.PlayerInfo
	(*Room)(nil),                   // 11: susubot.plugin.uno.Room
	(*Empty)(nil),                  // 12: susubot.plugin.uno.Empty
	(*BasicResponse)(nil),          // 13: susubot.plugin.uno.BasicResponse
	(*CreateRoomResponse)(nil),     // 14: susubot.plugin.uno.CreateRoomResponse
	(*GetRoomRequest)(nil),         // 15: susubot.plugin.uno.GetRoomRequest
	(*GetRoomResponse)(nil),        // 16: susubot.plugin.uno.GetRoomResponse
	(*GetRoomsResponse)(nil),       // 17: susubot.plugin.uno.GetRoomsResponse
	(*JoinRoomRequest)(nil),        // 18: susubot.plugin.uno.JoinRoomRequest
	(*JoinRoomResponse)(nil),       // 19: susubot.plugin.uno.JoinRoomResponse
	(*ExitRoomRequest)(nil),        // 20: susubot.plugin.uno.ExitRoomRequest
	(*ExitRoomResponse)(nil),       // 21: susubot.plugin.uno.ExitRoomResponse
	(*StartRoomRequest)(nil),       // 22: susubot.plugin.uno.StartRoomRequest
	(*DrawCardRequest)(nil),        // 23: susubot.plugin.uno.DrawCardRequest
	(*DrawCardResponse)(nil),       // 24: susubot.plugin.uno.DrawCardResponse
	(*SendCardActionRequest)(nil),  // 25: susubot.plugin.uno.SendCardActionRequest
	(*SendCardActionResponse)(nil), // 26: susubot.plugin.uno.SendCardActionResponse
}
var file_plugin_uno_protos_uno_uno_proto_depIdxs = []int32{
	6,  // 0: susubot.plugin.uno.Card.NormalCard:type_name -> susubot.plugin.uno.NormalCard
	7,  // 1: susubot.plugin.uno.Card.FeatureCard:type_name -> susubot.plugin.uno.FeatureCard
	2,  // 2: susubot.plugin.uno.NormalCard.Color:type_name -> susubot.plugin.uno.CardColor
	3,  // 3: susubot.plugin.uno.NormalCard.Number:type_name -> susubot.plugin.uno.CardNumber
	2,  // 4: susubot.plugin.uno.FeatureCard.Color:type_name -> susubot.plugin.uno.CardColor
	4,  // 5: susubot.plugin.uno.FeatureCard.FeatureCard:type_name -> susubot.plugin.uno.FeatureCards
	8,  // 6: susubot.plugin.uno.PlayerInfo.PlayerAccountInfo:type_name -> susubot.plugin.uno.PlayerAccountInfo
	9,  // 7: susubot.plugin.uno.PlayerInfo.PlayerRoomInfo:type_name -> susubot.plugin.uno.PlayerRoomInfo
	0,  // 8: susubot.plugin.uno.Room.Stage:type_name -> susubot.plugin.uno.Stage
	1,  // 9: susubot.plugin.uno.BasicResponse.err:type_name -> susubot.plugin.uno.Errors
	11, // 10: susubot.plugin.uno.GetRoomResponse.Info:type_name -> susubot.plugin.uno.Room
	11, // 11: susubot.plugin.uno.GetRoomsResponse.Infos:type_name -> susubot.plugin.uno.Room
	1,  // 12: susubot.plugin.uno.JoinRoomResponse.err:type_name -> susubot.plugin.uno.Errors
	8,  // 13: susubot.plugin.uno.JoinRoomResponse.Players:type_name -> susubot.plugin.uno.PlayerAccountInfo
	1,  // 14: susubot.plugin.uno.ExitRoomResponse.err:type_name -> susubot.plugin.uno.Errors
	8,  // 15: susubot.plugin.uno.ExitRoomResponse.Players:type_name -> susubot.plugin.uno.PlayerAccountInfo
	1,  // 16: susubot.plugin.uno.DrawCardResponse.err:type_name -> susubot.plugin.uno.Errors
	5,  // 17: susubot.plugin.uno.SendCardActionRequest.SendCards:type_name -> susubot.plugin.uno.Card
	1,  // 18: susubot.plugin.uno.SendCardActionResponse.err:type_name -> susubot.plugin.uno.Errors
	10, // 19: susubot.plugin.uno.SendCardActionResponse.NextOperator:type_name -> susubot.plugin.uno.PlayerInfo
	12, // 20: susubot.plugin.uno.uno.CreateRoom:input_type -> susubot.plugin.uno.Empty
	12, // 21: susubot.plugin.uno.uno.GetRooms:input_type -> susubot.plugin.uno.Empty
	15, // 22: susubot.plugin.uno.uno.GetRoom:input_type -> susubot.plugin.uno.GetRoomRequest
	18, // 23: susubot.plugin.uno.uno.JoinRoom:input_type -> susubot.plugin.uno.JoinRoomRequest
	20, // 24: susubot.plugin.uno.uno.ExitRoom:input_type -> susubot.plugin.uno.ExitRoomRequest
	22, // 25: susubot.plugin.uno.uno.StartRoom:input_type -> susubot.plugin.uno.StartRoomRequest
	23, // 26: susubot.plugin.uno.uno.DrawCard:input_type -> susubot.plugin.uno.DrawCardRequest
	25, // 27: susubot.plugin.uno.uno.SendCardAction:input_type -> susubot.plugin.uno.SendCardActionRequest
	14, // 28: susubot.plugin.uno.uno.CreateRoom:output_type -> susubot.plugin.uno.CreateRoomResponse
	17, // 29: susubot.plugin.uno.uno.GetRooms:output_type -> susubot.plugin.uno.GetRoomsResponse
	16, // 30: susubot.plugin.uno.uno.GetRoom:output_type -> susubot.plugin.uno.GetRoomResponse
	19, // 31: susubot.plugin.uno.uno.JoinRoom:output_type -> susubot.plugin.uno.JoinRoomResponse
	21, // 32: susubot.plugin.uno.uno.ExitRoom:output_type -> susubot.plugin.uno.ExitRoomResponse
	13, // 33: susubot.plugin.uno.uno.StartRoom:output_type -> susubot.plugin.uno.BasicResponse
	24, // 34: susubot.plugin.uno.uno.DrawCard:output_type -> susubot.plugin.uno.DrawCardResponse
	26, // 35: susubot.plugin.uno.uno.SendCardAction:output_type -> susubot.plugin.uno.SendCardActionResponse
	28, // [28:36] is the sub-list for method output_type
	20, // [20:28] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_plugin_uno_protos_uno_uno_proto_init() }
func file_plugin_uno_protos_uno_uno_proto_init() {
	if File_plugin_uno_protos_uno_uno_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plugin_uno_protos_uno_uno_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*NormalCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*FeatureCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PlayerAccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*PlayerRoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*BasicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CreateRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GetRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*GetRoomsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*JoinRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*JoinRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*ExitRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*ExitRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*StartRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*DrawCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*DrawCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*SendCardActionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_uno_protos_uno_uno_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*SendCardActionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_plugin_uno_protos_uno_uno_proto_msgTypes[0].OneofWrappers = []any{}
	file_plugin_uno_protos_uno_uno_proto_msgTypes[5].OneofWrappers = []any{}
	file_plugin_uno_protos_uno_uno_proto_msgTypes[8].OneofWrappers = []any{}
	file_plugin_uno_protos_uno_uno_proto_msgTypes[14].OneofWrappers = []any{}
	file_plugin_uno_protos_uno_uno_proto_msgTypes[16].OneofWrappers = []any{}
	file_plugin_uno_protos_uno_uno_proto_msgTypes[17].OneofWrappers = []any{}
	file_plugin_uno_protos_uno_uno_proto_msgTypes[19].OneofWrappers = []any{}
	file_plugin_uno_protos_uno_uno_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plugin_uno_protos_uno_uno_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_uno_protos_uno_uno_proto_goTypes,
		DependencyIndexes: file_plugin_uno_protos_uno_uno_proto_depIdxs,
		EnumInfos:         file_plugin_uno_protos_uno_uno_proto_enumTypes,
		MessageInfos:      file_plugin_uno_protos_uno_uno_proto_msgTypes,
	}.Build()
	File_plugin_uno_protos_uno_uno_proto = out.File
	file_plugin_uno_protos_uno_uno_proto_rawDesc = nil
	file_plugin_uno_protos_uno_uno_proto_goTypes = nil
	file_plugin_uno_protos_uno_uno_proto_depIdxs = nil
}
